import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Shared.module.css'

import Footer from '../../components/Footer'
import Login from '../../components/Login'

import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  return (
      <div className={styles.container}>
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={global.main}>
          <h2 className={styles.title}>
            <span>Languages Repository</span>
          </h2>
          <div>
            {router.basePath}
          </div>

          <div className={styles.grid}>
            <Login />
          </div>
        </main>
        <Footer />
      </div>
  )
}
