import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.css'

import Footer from '../components/Footer'
import Login from '../components/Login'

import { useRouter } from 'next/router';
import Link from 'next/link';

export default function Home() {
  const router = useRouter();
  return (
      <div className={styles.container}>
        <Head>
          <title>Languages Organizer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={global.main}>
          <h2 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Languages Organizer</a>
          </h2>

          
          <div className={styles.grid}>
            <div>Time to connect and share a piece of your country and your language with our community. Click here to <span><Link href="/login">Log In</Link></span></div>
          </div>
        </main>
        <Footer />
      </div>
  )
}
